# Problem statement.
### Build A Machine learning model to accuretely predict whether or not the patients in the dataset have diabetes or not?

## 2. Data Collection

### Import Necessary libraries.

In [58]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,precision_score,confusion_matrix,classification_report
from keras.layers import Dense,Dropout
from keras.models import Sequential
import numpy as np
from keras.models import load_model
import warnings
warnings.filterwarnings("ignore")

### Import data set.

In [6]:
diabetes_data = pd.read_csv("diabetes.csv")
diabetes_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

## 3. Data Understanding

In [7]:
diabetes_data.shape

(768, 9)

In [8]:
diabetes_data.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [9]:
diabetes_data.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [11]:
diabetes_data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

## 4. Data Preparation

In [17]:
X = diabetes_data.drop(labels='Outcome',axis = 1)
y = diabetes_data[["Outcome"]]

In [18]:
X.shape

(768, 8)

In [19]:
y.shape

(768, 1)

## 5. Model Building

In [22]:
model = Sequential()
model.add(Dense(12,input_dim = 8,kernel_initializer='uniform',activation='relu'))
model.add(Dense(8,kernel_initializer='uniform',activation='relu'))
model.add(Dense(1,kernel_initializer='uniform',activation='sigmoid'))

In [23]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [24]:
X_train,X_test,y_train,y_test =  train_test_split(X,y,test_size=0.20,random_state=12,stratify=y)

In [25]:
X_train.shape,y_train.shape

((614, 8), (614, 1))

In [26]:
X_test.shape,y_test.shape

((154, 8), (154, 1))

### Alert: Here's where you Need to apply Standarization.

In [28]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

## 6. Model Training || 7. Model Testing || 8. Evaluation

In [29]:
model.fit(X_train,y_train,batch_size=16,epochs=50,validation_split=0.2)

Epoch 1/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - accuracy: 0.6375 - loss: 0.6907 - val_accuracy: 0.6992 - val_loss: 0.6858
Epoch 2/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.6395 - loss: 0.6823 - val_accuracy: 0.6992 - val_loss: 0.6692
Epoch 3/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6395 - loss: 0.6583 - val_accuracy: 0.6992 - val_loss: 0.6300
Epoch 4/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.6395 - loss: 0.6097 - val_accuracy: 0.7154 - val_loss: 0.5771
Epoch 5/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7047 - loss: 0.5552 - val_accuracy: 0.7480 - val_loss: 0.5433
Epoch 6/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7739 - loss: 0.5195 - val_accuracy: 0.7398 - val_loss: 0.5372
Epoch 7/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7902 - loss: 0.5003 - val_accuracy: 0.7236 - val_loss: 0.5429
Epoch 8/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7923 - loss: 0.4858 - val_accuracy: 0.7317 - val_loss: 0.5461
Epoch 9/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7963 - loss: 0.4759 - val_accuracy: 0.7154 - val_loss: 0.5529
Epoch 10/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8024 - loss: 0.4673 - val_accuracy: 0.7073 - val_loss: 0.5559
Epoch 11/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7984 - loss: 0.4627 - val_accuracy: 0.7154 - val_loss: 0.5604
Epoch 12/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7943 - loss: 0.4573 - val_accuracy: 0.7073 - val_loss: 0.5661
Epoch 13/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8004 - loss: 0.4543 - val_accuracy: 0.7154 - val_loss: 0.5673
Epoch 14/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.8004 - loss: 0.4522 - val_accuracy: 0.7154 - val_loss: 0.5673
Epoch 15/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8045 - loss: 0.4505 - val_accuracy: 0.7154 - val_loss: 0.5725
Epoch 16/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8004 - loss: 0.4488 - val_accuracy: 0.7154 - val_loss: 0.5744
Epoch 17/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8065 - loss: 0.4485 - val_accuracy: 0.7154 - val_loss: 0.5757
Epoch 18/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8045 - loss: 0.4482 - val_accuracy: 0.7073 - val_loss: 0.5698
Epoch 19/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8004 - loss: 0.4455 - val_accuracy: 0.7073 - val_loss: 0.5690
Epoch 20/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8045 - loss: 0.4445 - val_accuracy: 0.6992 - val_loss: 0.5697
Epoch 21/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8004 - loss: 0.4438 - val_accuracy: 0.6992 - val_loss: 0.5699
Epoch 22/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7984 - loss: 0.4420 - val_accuracy: 0.6992 - val_loss: 0.5689
Epoch 23/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8024 - loss: 0.4414 - val_accuracy: 0.6992 - val_loss: 0.5708
Epoch 24/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7984 - loss: 0.4404 - val_accuracy: 0.7073 - val_loss: 0.5681
Epoch 25/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8004 - loss: 0.4388 - val_accuracy: 0.7073 - val_loss: 0.5651
Epoch 26/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8004 - loss: 0.4384 - val_accuracy: 0.7073 - val_loss: 0.5668
Epoch 27/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8024 - loss: 0.4371 - val_accuracy: 0.7154 - val_loss: 0.5635
Epoch 28/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7963 - loss: 0.4362 - val_accuracy: 0.7154 - val_loss: 0.5626
Epoch 29/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8004 - loss: 0.4353 - val_accuracy: 0.7154 - val_loss: 0.5635
Epoch 30/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7984 - loss: 0.4345 - val_accuracy: 0.7154 - val_loss: 0.5616
Epoch 31/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7984 - loss: 0.4334 - val_accuracy: 0.7154 - val_loss: 0.5620
Epoch 32/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7943 - loss: 0.4329 - val_accuracy: 0.7154 - val_loss: 0.5615
Epoch 33/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7943 - loss: 0.4322 - val_accuracy: 0.7154 - val_loss: 0.5619
Epoch 34/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8045 - loss: 0.4310 - val_accuracy: 0.7154 - val_loss: 0.5605
Epoch 35/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8004 - loss: 0.4316 - val_accuracy: 0.7154 - val_loss: 0.5585
Epoch 36/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8004 - loss: 0.4300 - val_accuracy: 0.7236 - val_loss: 0.5601
Epoch 37/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7984 - loss: 0.4292 - val_accuracy: 0.7236 - val_loss: 0.5591
Epoch 38/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7984 - loss: 0.4294 - val_accuracy: 0.7236 - val_loss: 0.5623
Epoch 39/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8024 - loss: 0.4284 - val_accuracy: 0.7317 - val_loss: 0.5601
Epoch 40/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8004 - loss: 0.4278 - val_accuracy: 0.7236 - val_loss: 0.5589
Epoch 41/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8086 - loss: 0.4268 - val_accuracy: 0.7236 - val_loss: 0.5596
Epoch 42/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8065 - loss: 0.4261 - val_accuracy: 0.7317 - val_loss: 0.5600
Epoch 43/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8065 - loss: 0.4257 - val_accuracy: 0.7317 - val_loss: 0.5580
Epoch 44/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.8004 - loss: 0.4252 - val_accuracy: 0.7317 - val_loss: 0.5601
Epoch 45/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.8045 - loss: 0.4244 - val_accuracy: 0.7317 - val_loss: 0.5598
Epoch 46/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8065 - loss: 0.4237 - val_accuracy: 0.7317 - val_loss: 0.5571
Epoch 47/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.8065 - loss: 0.4239 - val_accuracy: 0.7317 - val_loss: 0.5579
Epoch 48/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8065 - loss: 0.4230 - val_accuracy: 0.7317 - val_loss: 0.5578
Epoch 49/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.8045 - loss: 0.4227 - val_accuracy: 0.7317 - val_loss: 0.5608
Epoch 50/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.8106 - loss: 0.4220 - val_accuracy: 0.7317 - val_loss: 0.5596

## 9. Model Prediction.

In [34]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.50).astype(int)
y_pred

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0]])

In [54]:
print("Accuracy_Score:",round(accuracy_score(y_test,y_pred),4))
print("precision_Score:",round(precision_score(y_test,y_pred),3))
print("confusion_matrix:\n",confusion_matrix(y_test,y_pred))
print("Classification Report:",classification_report(y_test,y_pred))

Accuracy_Score: 0.7792
precision_Score: 0.7
confusion_matrix:
 [[85 15]
 [19 35]]
Classification Report:               precision    recall  f1-score   support

           0       0.82      0.85      0.83       100
           1       0.70      0.65      0.67        54

    accuracy                           0.78       154
   macro avg       0.76      0.75      0.75       154
weighted avg       0.78      0.78      0.78       154

In [57]:
model.save("Healthcare_intelligence.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

## ==============================================

## NEW INPUT PREDICTION:

### Write down the prediction pipeline you did while training

**input(array)-> Standardiziation-> model-> result(will be in array)-> so use typecasting-> return the single output**

In [68]:
intelligence_diabetes_file = load_model("Healthcare_intelligence.h5")

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [70]:
new_data = np.array([[9,148,72,35,0,33.6,0.627,50]])
new_data = scaler.transform(new_data)
prob = model.predict(new_data)

print("Probability:", prob)
final_class = (prob > 0.5).astype(int)
print("Final_Prediction:",final_class[0][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
Probability: [[0.74311715]]
Final_Prediction: 1